### ISSUE TITLE
Add Test Suite Group details on the email report

### ISSUE THREAD

**Issue by jkandasa** [reportengine/report-engine#7]
In the current design we don't have Test Suite Group details on the email report. Add Test Suite report with Group details (with ON and OFF option) on email report.

**Comment by LalatenduMohanty** [comment]
Yup. this will help to understand, how may test cases failed in each test group from the mail itself

**Comment by jkandasa** [comment]
Added this feature. 

Commit: https://github.com/jkandasa/report-engine/commit/b7b6bb342cce01d58edafe88df8610f61f940c0c
